name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main

env:
  REGISTRY: ebana.registry.twcstorage.ru
  IMAGE_NAME: market-product

jobs:

  ############################################################
  # TESTS
  ############################################################
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-root
      - name: Set Infisical
        run: |
          echo "===== Update .env ====="
          cat > .env <<EOF
          INFISICAL_HOST=${{ secrets.INFISICAL_HOST }}
          INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN }}
          ENVIRONMENT_SLUG=${{ secrets.ENVIRONMENT_SLUG_TESTS }}
          EOF
          chmod +x deploy/tests/*.sh

      - name: Run tests
        run: poetry run deploy/tests/test_entrypoint.sh


  ###########################################################
  # BUILD
  ###########################################################
  build:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: token
          password: ${{ secrets.REGISTRY_API_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ############################################################
  # DEPLOY (Blue-Green Zero Downtime)
  ############################################################
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            
            set -e

            APP_NAME="market-product"
            NETWORK="MARKET_NETWORK"
            REGISTRY="ebana.registry.twcstorage.ru"
            IMAGE="$REGISTRY/market-product:latest"

            echo "===== Docker login ====="
            echo "${{ secrets.REGISTRY_API_TOKEN }}" | docker login $REGISTRY -u token --password-stdin

            echo "===== Preparing project directory ====="
            mkdir -p apps
            cd apps

            if [ ! -d "MARKET_PRODUCT" ]; then
              git clone https://username:${{ secrets.ACCESS_TOKEN }}@github.com/pyostr-market/PRODUCT.git MARKET_PRODUCT
            fi

            cd MARKET_PRODUCT

            echo "===== Update code ====="
            git fetch origin
            git reset --hard origin/main

            echo "===== Update .env ====="
            cat > .env <<EOF
            INFISICAL_HOST=${{ secrets.INFISICAL_HOST }}
            INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN }}
            ENVIRONMENT_SLUG=${{ secrets.ENVIRONMENT_SLUG }}
            EOF

            echo "===== Pull latest image ====="
            docker pull $IMAGE

            echo "===== Detect active container ====="

            BLUE_RUNNING=false
            GREEN_RUNNING=false

            if docker ps --format '{{.Names}}' | grep -q "^$APP_NAME-blue$"; then
              BLUE_RUNNING=true
            fi

            if docker ps --format '{{.Names}}' | grep -q "^$APP_NAME-green$"; then
              GREEN_RUNNING=true
            fi

            if [ "$BLUE_RUNNING" = true ]; then
              ACTIVE="blue"
              TARGET="green"
            elif [ "$GREEN_RUNNING" = true ]; then
              ACTIVE="green"
              TARGET="blue"
            else
              echo "First deploy â€” no active container"
              ACTIVE=""
              TARGET="blue"
            fi

            echo "Active: $ACTIVE"
            echo "Deploying to: $TARGET"

            echo "===== Remove old TARGET ====="
            docker compose stop web-$TARGET 2>/dev/null || true
            docker compose rm -f web-$TARGET 2>/dev/null || true

            echo "===== Start TARGET ====="
            docker compose up -d web-$TARGET

            echo "===== Wait for healthcheck ====="
            ATTEMPTS=60

            until [ "$(docker inspect --format='{{.State.Health.Status}}' $APP_NAME-$TARGET 2>/dev/null)" = "healthy" ]; do
              ATTEMPTS=$((ATTEMPTS-1))
              if [ $ATTEMPTS -le 0 ]; then
                echo "New container is not healthy. Rollback."
                docker compose stop web-$TARGET || true
                docker compose rm -f web-$TARGET || true
                exit 1
              fi
              sleep 2
            done

            echo "===== TARGET healthy ====="

            echo "===== Switch network alias ====="

            docker network connect --alias web-product $NETWORK $APP_NAME-$TARGET 2>/dev/null || true

            if [ -n "$ACTIVE" ]; then
              docker network disconnect $NETWORK $APP_NAME-$ACTIVE 2>/dev/null || true
            fi

            echo "===== Stop old container ====="
            if [ -n "$ACTIVE" ]; then
              docker compose stop web-$ACTIVE || true
            fi

            echo "===== Cleanup dangling images ====="
            docker image prune -f

            echo "===== DEPLOY SUCCESS (Blue-Green Zero-Downtime) ====="
